version: '3.9'

# DailyDevQ 백엔드 프로덕션 Docker Compose

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dailydevq-backend-prod
    env_file:
      - .env.production
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dailydevq-prod

networks:
  dailydevq-prod:
    driver: bridge
